### ISSUE TITLE
AWS S3 plugin,  not working

### ISSUE THREAD

**Issue by thushy07** [hersche/YouPHPTube-Docs#1]
i bought the AWS S3 plugin, looks like it's installed correctly, but for some reason its not working.
any help will be appreciated 

Thank you

**Comment by DanielnetoDotCom** [comment]
Please open an issue here https://github.com/WWBN/AVideo/issues

and provide your log file

**Comment by hersche** [comment]
this repo is deprecated and i left the project meanwhile.. i will delete the repo soon, as the initial idea to make docs remained unused.
